[versions]
appVersion = "0.1.0"

androidGradlePlugin = "8.11.1"
kotlin = "2.2.0"
ksp = "2.2.0-2.0.2"
kotest = "5.9.1"
junit = "5.13.4"
mockk = "1.14.5"
jproc = "2.8.2"
koin = "4.1.0"
clojure = "1.12.1"
shadowJar = "8.1.1"
ktor = "3.2.3"
logback = "1.5.18"
timber = "5.0.1"
multidex = "2.0.1"
room = "2.7.2"
junit4 = "4.13.2"
coreKtx = "1.16.0"
androidxJunit = "1.3.0"
espressoCore = "3.7.0"
lifecycle = "2.9.2"
activityCompose = "1.10.1"
composeBom = "2025.07.00"
serializationJson = "1.9.0"
jackson = "2.19.2"
arrow = "2.1.2"
decompose = "3.3.0"
materialIcons = "1.7.8"
viewMaterial = "1.12.0"
hibernate = "5.6.0.Final"
h2 = "2.3.232"
coil = "2.7.0"
dadb = "1.2.10"
mordant = "3.0.2"
truth = "1.4.4"
navigation = "1.0.0"
constraintLayoutCompose = "1.1.1"
retrofit = "3.0.0"
moshi = "1.15.2"
okHttpLogger = "5.1.0"
recyclerView = "1.4.0"
constraintLayout = "2.2.1"
kotlinGradlePlugin = "2.0.0"
gson = "2.13.1"
ksprefs = "2.4.1"
foundation = "1.10.1"
uiUnit = "1.10.1"
flippable = "1.5.4"

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
shadowjar = { id = "com.github.johnrengelman.shadow", version.ref = "shadowJar" }
androidApplication = { id = "com.android.application", version.ref = "androidGradlePlugin" }
kotlinAndroid = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
parcelize = { id = "org.jetbrains.kotlin.plugin.parcelize", version.ref = "kotlin" }
kapt = { id = "org.jetbrains.kotlin.kapt", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
kotlinSerialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
jpa = { id = "org.jetbrains.kotlin.plugin.jpa", version.ref = "kotlin" }
composeCompiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }

[libraries]
kotlin-reflect = { module = "org.jetbrains.kotlin:kotlin-reflect", version.ref = "kotlin" }
kotlinx-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "serializationJson" }
kotest-assertions = { module = "io.kotest:kotest-assertions-core-jvm", version.ref = "kotest" }
kotest-runner = { module = "io.kotest:kotest-runner-junit5-jvm", version.ref = "kotest" }
junit-engine = { module = "org.junit.jupiter:junit-jupiter-engine", version.ref = "junit" }
mockk = { module = "io.mockk:mockk", version.ref = "mockk" }
jproc = { module = "org.buildobjects:jproc", version.ref = "jproc" }
clojure = { module = "org.clojure:clojure", version.ref = "clojure" }
koin = { module = "io.insert-koin:koin-core", version.ref = "koin" }
koin-android = { module = "io.insert-koin:koin-android", version.ref = "koin" }
junit4 = { group = "junit", name = "junit", version.ref = "junit4" }
timber = { module = "com.jakewharton.timber:timber", version.ref = "timber" }
androidx-multidex = { module = "androidx.multidex:multidex", version.ref = "multidex" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "androidxJunit" }
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycle" }
androidx-lifecycle-vm = { module = "androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "lifecycle" }
androidx-lifecycle-compose = { module = "androidx.lifecycle:lifecycle-runtime-compose", version.ref = "lifecycle" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
androidx-navigation3Runtime = { module = "androidx.navigation3:navigation3-runtime", version.ref = "navigation" }
androidx-navigation3Ui = { module = "androidx.navigation3:navigation3-ui", version.ref = "navigation" }
androidx-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
androidx-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
androidx-ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }
androidx-material3 = { group = "androidx.compose.material3", name = "material3" }
androidx-viewMaterial = { module = "com.google.android.material:material", version.ref = "viewMaterial" }
androidx-icons = { module = "androidx.compose.material:material-icons-extended", version.ref = "materialIcons" }
androidx-constraintLayoutCompose = { module = "androidx.constraintlayout:constraintlayout-compose", version.ref = "constraintLayoutCompose" }
androidx-recyclerView = { module = "androidx.recyclerview:recyclerview", version.ref = "recyclerView" }
androidx-constraintLayout = { module = "androidx.constraintlayout:constraintlayout", version.ref = "constraintLayout" }
ktor-serverCore = { module = "io.ktor:ktor-server-core", version.ref = "ktor" }
ktor-serverNetty = { module = "io.ktor:ktor-server-netty", version.ref = "ktor" }
ktor-serverWebsockets = { module = "io.ktor:ktor-server-websockets", version.ref = "ktor" }
ktor-serverNegotiation = { module = "io.ktor:ktor-server-content-negotiation", version.ref = "ktor" }
ktor-serverAuth = { module = "io.ktor:ktor-server-auth", version.ref = "ktor" }
ktor-serverAuthjwt = { module = "io.ktor:ktor-server-auth-jwt", version.ref = "ktor" }
ktor-serverCors = { module = "io.ktor:ktor-server-cors", version.ref = "ktor" }
ktor-serverKeysore = { module = "io.ktor:ktor-network-tls-certificates", version.ref = "ktor" }
ktor-clientCore = { module = "io.ktor:ktor-client-core", version.ref = "ktor" }
ktor-clientWebsockets = { module = "io.ktor:ktor-client-websockets", version.ref = "ktor" }
ktor-clientCio = { module = "io.ktor:ktor-client-cio", version.ref = "ktor" }
ktor-clientOkhttp = { module = "io.ktor:ktor-client-okhttp", version.ref = "ktor" }
ktor-clientNegotiation = { module = "io.ktor:ktor-client-content-negotiation", version.ref = "ktor" }
ktor-clientLogging = { module = "io.ktor:ktor-client-logging", version.ref = "ktor" }
ktor-clientAuth = { module = "io.ktor:ktor-client-auth", version.ref = "ktor" }
ktor-serializationJson = { module = "io.ktor:ktor-serialization-kotlinx-json", version.ref = "ktor" }
logback = { module = "ch.qos.logback:logback-classic", version.ref = "logback" }
room-compiler = { module = "androidx.room:room-compiler", version.ref = "room" }
room-runtime = { module = "androidx.room:room-runtime", version.ref = "room" }
room-test = { module = "androidx.room:room-testing", version.ref = "room" }
jackson-kotlin = { module = "com.fasterxml.jackson.module:jackson-module-kotlin", version.ref = "jackson" }
jackson-yaml = { module = "com.fasterxml.jackson.dataformat:jackson-dataformat-yaml", version.ref = "jackson" }
arrowCore = { module = "io.arrow-kt:arrow-core", version.ref = "arrow" }
arrowCoroutines = { module = "io.arrow-kt:arrow-fx-coroutines", version.ref = "arrow" }
decompose = { module = "com.arkivanov.decompose:decompose", version.ref = "decompose" }
decompose-extensions = { module = "com.arkivanov.decompose:extensions-compose-android", version.ref = "decompose" }
db-h2 = { module = "com.h2database:h2", version.ref = "h2" }
db-hibernate = { module = "org.hibernate:hibernate-core", version.ref = "hibernate" }
coil = { module = "io.coil-kt:coil-compose", version.ref = "coil" }
dadb = { module = "dev.mobile:dadb", version.ref = "dadb" }
mordant = { module = "com.github.ajalt.mordant:mordant", version.ref = "mordant" }
truth = { module = "com.google.truth:truth", version.ref = "truth" }
retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }
retrofitMoshiConverter = { module = "com.squareup.retrofit2:converter-moshi", version.ref = "retrofit" }
moshi = { module = "com.squareup.moshi:moshi", version.ref = "moshi" }
moshiComplier = { module = "com.squareup.moshi:moshi-kotlin-codegen", version.ref = "moshi" }
okHttpLogger = { module = "com.squareup.okhttp3:logging-interceptor", version.ref = "okHttpLogger" }
kotlin-gradle-plugin = { group = "org.jetbrains.kotlin", name = "kotlin-gradle-plugin", version.ref = "kotlin" }
gson = { module = "com.google.code.gson:gson", version.ref = "gson" }
ksprefs = { module = "com.github.cioccarellia:ksprefs", version.ref = "ksprefs" }
androidx-compose-foundation = { group = "androidx.compose.foundation", name = "foundation", version.ref = "foundation" }
androidx-compose-ui-unit = { group = "androidx.compose.ui", name = "ui-unit", version.ref = "uiUnit" }
flippable = { group = "com.wajahatkarim", name = "flippable", version.ref = "flippable" }